// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.zhss.dfs.namenode.rpc.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\031com.zhss.dfs." +
      "namenode.rpc\032\026NameNodeRpcModel.proto2\223\004\n" +
      "\017NameNodeService\022c\n\010register\022*.com.zhss." +
      "dfs.namenode.rpc.RegisterRequest\032+.com.z" +
      "hss.dfs.namenode.rpc.RegisterResponse\022f\n" +
      "\theartbeat\022+.com.zhss.dfs.namenode.rpc.H" +
      "eartbeatRequest\032,.com.zhss.dfs.namenode." +
      "rpc.HeartbeatResponse\022Z\n\005mkdir\022\'.com.zhs" +
      "s.dfs.namenode.rpc.MkdirRequest\032(.com.zh" +
      "ss.dfs.namenode.rpc.MkdirResponse\022c\n\010shu",
      "tdown\022*.com.zhss.dfs.namenode.rpc.Shutdo" +
      "wnRequest\032+.com.zhss.dfs.namenode.rpc.Sh" +
      "utdownResponse\022r\n\rfetchEditsLog\022/.com.zh" +
      "ss.dfs.namenode.rpc.FetchEditsLogRequest" +
      "\0320.com.zhss.dfs.namenode.rpc.FetchEditsL" +
      "ogResponseB5\n!com.zhss.dfs.namenode.rpc." +
      "serviceB\016NameNodeServerP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zhss.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.zhss.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
